### ISSUE TITLE
ERROR: for terrama2_webapp_1

### ISSUE THREAD

**Issue by miguelfs** [TerraMA2/docker#96]
Oi, pessoal. Segui os passos indicados no README, porém tive um problema no seguinte:

Ao chamar o ./configure.sh, após efetuar os downloads das imagens, tomei a seguinte mensagem:

> Creating terrama2_view_1         ... done
Creating terrama2_collector_1    ... done
Creating terrama2_webapp_1       ... error
Creating terrama2_interpolator_1 ... done
Creating terrama2_analysis_1     ... done
Creating terrama2_alert_1        ... done
Creating terrama2_geoserver      ... 

> ERROR: for terrama2_webapp_1  Cannot start service webapp: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:60: mounting "/Users/miguel/Developer/docker/conf/terrama2_webapp_settings.json" to rootfs at "/var/lib/docker/overlay2/343053734ea07b5974c92c1a8376464f7d3ffc768406f7a9e62efdf6a08b9f08/merged/opt/terrama2/4.1.1/webapp/config/settings.json" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and iCreating terrama2_geoserver      ... done

Conseguem me ajudar? Tanto eu quanto um colega utilizando Windows tivemos o mesmo problema.

Estou usando macOS Big Sur 11.2.3.

**Comment by MarceloPilatti** [comment]
Olá, da uma olhada no arquivo "conf/terrama2_webapp_settings.json". Provavelmente ele virou um diretório, as vezes acontece isso. Exclui ele, roda o docker-compose -p terrama2 down e depois o up para ver se funciona.

**Comment by miguelfs** [comment]
foi :)

**Comment by miguelfs** [comment]
Com o up aparentemente dá bom, com o down ele gera novamente a pasta:

> MacBook-Air-de-Miguel:docker miguel$ rm -r conf/terrama2_webapp_settings.json/
MacBook-Air-de-Miguel:docker miguel$ docker-compose -p terrama2 down
Stopping terrama2_geoserver      ... done
Stopping terrama2_view_1         ... done
Stopping terrama2_alert_1        ... done
Stopping terrama2_interpolator_1 ... done
Stopping terrama2_collector_1    ... done
Stopping terrama2_analysis_1     ... done
Removing terrama2_webapp_1       ... done
Removing terrama2_geoserver      ... done
Removing terrama2_view_1         ... done
Removing terrama2_alert_1        ... done
Removing terrama2_interpolator_1 ... done
Removing terrama2_collector_1    ... done
Removing terrama2_analysis_1     ... done
Removing network terrama2_net
MacBook-Air-de-Miguel:docker miguel$ docker-compose -p terrama2 up
Docker Compose is now in the Docker CLI, try `docker compose up`

>Creating network "terrama2_net" with the default driver
Creating terrama2_webapp_1       ... error
Creating terrama2_interpolator_1 ... done
Creating terrama2_view_1         ... done
Creating terrama2_analysis_1     ... done
Creating terrama2_geoserver      ... 
Creating terrama2_collector_1    ... done
Creating terrama2_alert_1        ... done

>ERROR: for terrama2_webapp_1  Cannot start service webapp: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:60: mounting "/host_mnt/Users/miguel/Developer/docker/Creating terrama2_geoserver      ... done
465/merged/opt/terrama2/4.1.1/webapp/config/db.json" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by MarceloPilatti** [comment]
Acho que aconteceu a mesma coisa com o arquivo "conf/terrama2_webapp_db.json"
